### ISSUE TITLE
sometimes grunt-help-command is `nil --help --no-color`

### ISSUE THREAD

**Issue by gempesaw** [gempesaw/grunt.el#13]
i guess if `grunt-help-command` is initialized before `grunt-base-command` is, then `grunt-command` is nil so `grunt-help-command` becomes `nil --help --no-color`? or something ?

i'm not sure how i get my emacs in to this state...

**Comment by domtronn** [comment]
I noticed this after #8...

For me it seemed to be fixed by loading grunt later in my `init.el`. Doing some further debug, it looks like the package is dependent on your `exec-path` being set properly. 

My `grunt` is installed in `/usr/local/bin` but I add this to my `exec-path` in my `init.el`
```elisp
(setq exec-path '("/usr/local/bin" "/usr/bin" "/bin" ))
```
So it looks like requiring the package when the `exec-path` doesn't contain the path for the `grunt` executable breaks the setup of the custom variables!

Do you set an `exec-path` anywhere? Do you want try requiring the package after adding the location of `grunt` to your `exec-path`? Maybe we should just mention this in the `README.md`?

**Comment by gempesaw** [comment]
ah yeah that sounds like exactly the solution, I do set `exec-path` at some point, probably after loading `grunt`, as per the evidence. 

we can make a mention in the readme. perhaps it should also check that `grunt-base-command` and `grunt-help-command` aren't nil when the user invokes `(grunt-exec)`, and try to reassign them based on `(executable-find)` at that time, along with a helpful error message if the `executable-find` fails. hummmm
