### ISSUE TITLE
Errors in typescript compilation generate an endless stream of output

### ISSUE THREAD

**Issue by abingham** [gempesaw/grunt.el#6]
I'm using grunt to compile typescript using the [grunt-tsc](https://github.com/rodzewich/grunt-tsc) plugin. If there's an error in my code when I run `grunt-exec`, then the output buffer gets filled with an endless stream of `>>` prompts. It looks something like this:
```
Running "tsc:task_name" (tsc) task
options: target="ES5", module="amd", declaration="false", comments="true", sourcemap="false", implicitAny="true", preserveConstEnums="false", sourceRoot=null, mapRoot=null, version="1.5", compiler="/Users/austinbingham/projects/fracreg/node_modules/grunt-tsc/bin/v1.5/tsc.js", node="/usr/local/Cellar/node/0.12.0/bin/node", library="false", system=[], references=[]
>> 
>> 
>> 
>> 
>> 
>> 
. . . etc, these double-chevrons keep getting generated forever . . .
```

Interestingly, I see similar behavior when I run grunt through `eshell`, though not when I run it through `ansi-term` or `multi-term`.

This is using emacs 24.4.1 on OS X.

**Comment by gempesaw** [comment]
Hm, I have noticed some unintentional output when shell commands try to do animations in Emacs's fake shells. It has something to do with the way that Emacs fails to handle color sequences or something, although usually those look more like `-[0G\[0G|[0G/[0G-[0G\[0G...` I think, I've never seen the repeated `>>`'s.

I'd expect similar poor behavior from <kbd>M-x shell</kbd> as well. It working in `ansi-term` and `multi-term` makes sense since I think those are much closer to an actual terminal/better at handling this stuff. Perhaps I'll go hunt down what they're doing to their buffers to handle colors, or whatever thing this is.

**Comment by abingham** [comment]
FWIW, I changed my `grunt-base-command` to pass `--no-color` to grunt, but the problem persists.

**Comment by gempesaw** [comment]
oh! thanks for the additional info.

is the project you're compiling with grunt-tsc open-source, by any chance? so i don't have to find my own typescript project to test with :P

oh, maybe i can just run the grunt-tsc tests. hm!

**Comment by abingham** [comment]
Yes, the project is [fracreg](https://bitbucket.org/sixty-north/fracreg). It's in a bit of a state of flux right now (i.e. possibly in shambles), but running grunt should still work, I think.

**Comment by gempesaw** [comment]
hmmm i think there's a race condition where the grunt task looks for `process.stdout.columns` before emacs is able to `(set-process-window-size)`, but hooopefully it's rare? =/

@abingham lemme know if this works for you. thanks!

**Comment by abingham** [comment]
Thanks! This seems to fix the problem I was seeing. `grunt-exec` now works fine in the presence of errors.
